### ISSUE TITLE
Recommend best standards for logging

### ISSUE THREAD

**Issue by callumrollo** [callumrollo/erddaplogs#1]
Suggested by @mwengren

We should recommend that users make their logs as useful as possible by e.g. increasing log retention so that logs are not erased and/or backing up logs to another machine for analysis

**Comment by mwengren** [comment]
Something along the lines of the 'Combined log' format per https://httpd.apache.org/docs/2.4/logs.html is what I thought might be appropriate to recommend.  (search for 'Combined log format' which is under 'Access logs' on that page).  Apparently the Apache docs were made before HTML anchor tags existed to be able to link directly to the relevant header :).

Or, there might be something more appropriate for ERDDAP that this group could recommend and document somewhere.  

One suggestion where these best practices could be documented might be: https://github.com/ioos/erddap-gold-standard, although I am not sure where that specific config detail might go in that repo.
