### ISSUE TITLE
Think about data retention

### ISSUE THREAD

**Issue by callumrollo** [callumrollo/erddaplogs#43]
Don't retain those logs! Anonymize them with Chris' function

**Comment by ChrisJohnNOAA** [comment]
There was mention of setting this up to be runnable on a schedule/cron job.

I was wondering if there'd be interest in making the anonymized csv (and maybe the location) available as an ERDDAP dataset.

**Comment by callumrollo** [comment]
how delightfully meta! Yeah we could do that for sure
