### ISSUE TITLE
Lists of erddap protocols

### ISSUE THREAD

**Issue by callumrollo** [callumrollo/erddaplogs#61]
The first part of an erddap url (after removing a potential language tag #60) should be a protocol. e.g.:

/erddap/tabledap
/erddap/wms

Sometimes it's a page like

/erddap/index

I have made a list of potential protocols/erddap home pages here https://github.com/callumrollo/erddaplogs/blob/b71a5c08ddade8ba27cbec9d7524c87ef8d967a1/erddaplogs/logparse.py#L203

This covers 99.95 % of the valid requests in our test data

![image](https://github.com/callumrollo/erddaplogs/assets/28703282/f73c7c4a-dffd-4c03-a54f-f37ea0e6875b)

Does this cover all the bases? Are there any other protocols/pages that we need to classify? @ChrisJohnNOAA

**Comment by ChrisJohnNOAA** [comment]
Based on [Erddap.java Lines 608-721](https://github.com/ERDDAP/erddap/blob/main/WEB-INF/classes/gov/noaa/pfel/erddap/Erddap.java#L608-L721)

protocols I think you missed:
download, images, public, opensearch1.1, login, loginGoogle, loginOrcid, logout, setDatasetFlag, sitemap, dataProviderForm, dataProviderForm1, dataProviderForm2, dataProviderForm3, dataProviderForm4, dataProviderFormDone, version, version_string

For some servers these might get heavy usage (like login).

partially done protocols that might be enabled in the future:
sos, wcs

protocols I believe are in your list
griddap, tabledap, files, wms, index, metadata, rss, search, categorize, info, information, legal, rest, slidesorter, status, subscriptions, convert, outOfDateDatasets

The dataProviderForm ones can probably all be grouped together. The login ones can also probably be grouped together. The original url should have the exact page if that is needed for analysis later.
